import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    cardContainer: {
        width: '90%',
        backgroundColor: '#1e2a38', 
        borderRadius: 20,
        padding: 25,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.5,
        shadowRadius: 10,
        elevation: 12,
        marginBottom: 30,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#2a9d8f',
    },
    restaurantName: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#f9fafb',
        textAlign: 'center',
        marginBottom: 15,
        textShadowColor: 'rgba(0, 0, 0, 0.7)',
        textShadowOffset: { width: 1, height: 2 },
        textShadowRadius: 3,
        letterSpacing: 1,
    },
    description: {
        fontSize: 16,
        color: '#d1d1d1',
        textAlign: 'justify',
        marginBottom: 20,
        lineHeight: 24,
        paddingHorizontal: 5,
    },
    infoContainer: {
        width: '100%',
    },
    label: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#a3a3a3',
        marginTop: 10,
        letterSpacing: 0.5,
    },
    text: {
        fontSize: 15,
        color: '#c5c5c5',
        marginBottom: 6,
        paddingVertical: 8,
        paddingHorizontal: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 10,
        textAlign: 'center',
    },
    dataContainer: {
        backgroundColor: '#243447',
        borderRadius: 12,
        padding: 10,
        marginBottom: 15,
    },
    locationButton: {
        backgroundColor: '#2a9d8f',
        paddingVertical: 12,
        paddingHorizontal: 25,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
        elevation: 8,
    },
    locationButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        letterSpacing: 1,
    },
});

export default styles;
